version: "3.8"

services:
  frontend:
    image: ffrycz/image_search_app-frontend:latest
    # build: frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - clip
    networks:
      - app-network

  backend:
    image: ffrycz/image_search_app-backend:latest
    # build: ./backend
    container_name: flask-backend
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      PIXABAY_API_KEY_FILE: /run/secrets/pixabay_api_key
      # PEXELS_API_KEY_FILE: /run/secrets/pexels_api_key
      UNSPLASH_API_KEY_FILE: /run/secrets/unsplash_api_key
      CAPTCHA_KEY_FILE: /run/secrets/captha_key
      MODEL_HOST: clip
      MODEL_PORT: 4000
    ports:
      - 5001:5000
    networks:
      - app-network
      - redis-network
      - database-network
      - keycloak-network
    depends_on:
      - clip
      - database
      - keycloak
    volumes:
      - shared_images:/app/uploads
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - db_password
      - pixabay_api_key
      - pexels_api_key
      - unsplash_api_key
      - captha_key

  memoryStore:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - clip
    networks:
      - redis-network

  database:
    image: mysql:8
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: photos_db
    depends_on:
      - clip
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - database-network
    secrets:
      - db_password

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    depends_on:
      - clip
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
      - clip
    networks:
      - keycloak-network

  clip:
    image: ffrycz/image_search_app-clip:latest
    # build: ./clip
    container_name: clip
    ports:
      - 4000:4000
    volumes:
      - shared_images:/data/images
      - clip-cache:/app/cache
      # - ./clip:/app
      - ./clip/app:/app
    networks:
      - app-network

  worker:
    build: ./backend
    container_name: embedding-worker
    command: python -m app.worker
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      PIXABAY_API_KEY_FILE: /run/secrets/pixabay_api_key
      MODEL_HOST: clip
      MODEL_PORT: 4000
    volumes:
      - shared_images:/app/uploads
    networks:
      - app-network
      - database-network
      - redis-network
    depends_on:
      - database
      - memoryStore
      - clip
    secrets:
      - db_password
      - pixabay_api_key
    restart: unless-stopped

volumes:
  db-data:
  shared_images:
  clip-cache:
  keycloak-data:

networks:
  app-network:
    driver: bridge
  redis-network:
    driver: bridge
  database-network:
    driver: bridge
  keycloak-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  pixabay_api_key:
    file: ./secrets/pixabay_api_key.txt
  pexels_api_key:
    file: ./secrets/pexels_api_key.txt
  unsplash_api_key:
    file: ./secrets/unsplash_api_key.txt
  kc_admin_password:
    file: ./secrets/kc_admin_password.txt
  kc_db_password:
    file: ./secrets/kc_db_password.txt
  captha_key:
    file: ./secrets/reCaptcha_key.txt
