version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - clip
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: flask-backend
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      PIXABAY_API_KEY_FILE: /run/secrets/pixabay_api_key
      MODEL_HOST: clip
      MODEL_PORT: 4000
    ports:
      - 5001:5000
    networks:
      - app-network
      - redis-network
      - database-network
    depends_on:
      - clip
      - database
    volumes:
      - shared_images:/app/uploads
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - db_password
      - pixabay_api_key

  memoryStore:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - clip
    networks:
      - redis-network

  database:
    image: mysql:8
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: photos_db
    depends_on:
      - clip
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - database-network
    secrets:
      - db_password

  # keycloak-db:
  #   image: postgres:15
  #   container_name: keycloak-db
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: /run/secrets/kc_db_password
  #   depends_on:
  #     - clip
  #   volumes:
  #     - /var/lib/postgresql/keycloak_data:/var/lib/postgresql/data
  #   networks:
  #     - keycloak-network
  #   secrets:
  #     - kc_db_password

  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.2.5
  #   container_name: keycloak
  #   command: start-dev
  #   environment:
  #     KC_DB: postgres
  #     KC_DB_URL_HOST: keycloak-db
  #     KC_DB_URL_DATABASE: keycloak
  #     KC_DB_USERNAME: keycloak
  #     KC_DB_PASSWORD: /run/secrets/kc_db_password
  #     KC_HOSTNAME: localhost
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: /run/secrets/kc_admin_password
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - keycloak-db
  #     - clip
  #   volumes:
  #     - ./keycloak-import:/opt/keycloak/data/import
  #   networks:
  #     - keycloak-network
  #   secrets:
  #     - kc_admin_password
  #     - kc_db_password

  clip:
    build: ./clip
    container_name: clip
    ports:
      - 4000:4000
    volumes:
      - shared_images:/data/images
    networks:
      - app-network

volumes:
  db-data:
  shared_images:

networks:
  app-network:
    driver: bridge
  redis-network:
    driver: bridge
  database-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  pixabay_api_key:
    file: ./secrets/pixabay_api_key.txt
