name: Deploy to VPS

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish Backend
        run: |
          docker build --platform linux/amd64,linux/arm64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-backend:latest ./backend
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-backend:latest
      - name: Build and Publish Frontend
        run: |
          docker build --platform linux/amd64,linux/arm64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-frontend:latest ./frontend
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-frontend:latest
      - name: Build and Publish CLIP Model Server
        run: |
          docker build --platform linux/amd64,linux/arm64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-clip ./clip
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-clip:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add server to known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          VPS_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}

      - name: SSH into server and pull latest
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull
            docker compose up -d
            exit

# git pull origin main

