name: Deploy to VPS

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Check If Backend Changed
        id: backend_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/'; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Check If Frontend Changed
        id: frontend_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Check If Clip Changed
        id: clip_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^clip/'; then
            echo "clip_changed=true" >> $GITHUB_OUTPUT
          else
            echo "clip_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Build and Publish Backend
        if: steps.backend_changes.outputs.backend_changed == 'true'
        run: |
          docker build --platform linux/amd64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-backend:latest ./backend
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-backend:latest
      - name: Build and Publish Frontend
        if: steps.frontend_changes.outputs.frontend_changed == 'true'
        run: |
          docker build --platform linux/amd64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-frontend:latest ./frontend
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-frontend:latest
      - name: Build and Publish CLIP Model Server
        if: steps.clip_changes.outputs.clip_changed == 'true'
        run: |
          docker build --platform linux/amd64 -t ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-clip ./clip
          docker push ${{env.REGISTRY}}/${{ env.OWNER }}/image_search_app-clip:latest
    outputs:
      backend_changed: ${{ steps.backend_changes.outputs.backend_changed }}
      frontend_changed: ${{ steps.frontend_changes.outputs.frontend_changed }}
      clip_changed: ${{ steps.clip_changes.outputs.clip_changed }}
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    if: |
      needs.publish.outputs.backend_changed == 'true' || 
      needs.publish.outputs.frontend_changed == 'true' || 
      needs.publish.outputs.clip_changed == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add server to known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          VPS_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}

      - name: SSH into server and pull latest
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull
            docker compose up -d
            exit

# git pull origin main

